version: '2'
services:
  web:
    build:
      context: ./NodeJS
    image: guidoin/cv-node-app
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db:cassandra-db-alias
    restart: always
    container_name: cv-site-api
    networks:
    - external
    - internal
  db:
    build:
      context: ./CassandraDB
    image: guidoin/cassandra-cv
    container_name: cassandra-db
    networks:
      - internal
    environment:
      CASSANDRA_NUM_TOKENS: '256'
  db2:
    image: cassandra
    container_name: cassandra-db-slave
    networks:
      - internal
    depends_on:
      - db
    links:
      - db:cassandra-db-master
    environment:
      CASSANDRA_SEEDS: cassandra-db
  static-files:
    image: nginx:alpine
    volumes:
      - ./Site:/usr/share/nginx/html
    container_name: cv-site-static
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    networks:
    - external
networks:
  external:
  internal:
